// 'use client'

import './globals.css'

export const metadata = {
  title: {
    template:'%s | Acme',
    default: 'Profile',
  },
  description: 'Generated by create next app',
  // themeColor: '#201c2e',
}

export default function RootLayout({ children }) {
 
  return (
    <html lang="en" className="m-0 p-0">
    
      <body className=" overflow-x-hidden w-screen">
          {children}
      </body>
    </html>
  )
}
