import './globals.css'

export const metadata = {
  title: 'My Profile',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-green-500' >{children}</body>
    </html>
  )
}
